name: Comment

on: 
  pull_request:
    branches: ["*"]

jobs:
  comment: # the job's name
    runs-on: ubuntu-latest
    steps:
      - env: 
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr comment $PR_NUMBERS --body "hi from github" --repo $GITHUB_REPOSITORY

